name: "publish-rust"
description: "Publishes Rust library to crates.io"
inputs:
  crates-token:
    description: "used for authenticating towards crates.io"
    required: true
  version:
    description: "the version to release under (e.g. `1.2.3-dev.1`)"
    required: true
  dry-run:
    description: "'true' = only log potential result; 'false' = publish'"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Rust
      uses: "./.github/actions/rust/setup"
      with:
        os: ${{ runner.os }}
        job: ${{ github.job }}

    - name: Install cargo-release
      shell: bash
      run: cargo install --version =0.25 cargo-release

    - name: Publish library to crates.io
      shell: bash
      run: |
        echo "dry-run: '${{ inputs.dry-run }}'"
        echo "version: '${{ inputs.version }}'"
        cargo login ${{ inputs.crates-token }}
        cargo release config
        cargo release version --verbose --execute --no-confirm ${{ inputs.version }}
        cargo release publish --verbose $(if [ "${{ inputs.dry-run }}" = "false" ]; then echo --execute --no-confirm; fi)
